// app/components/pintura/presets/vue/v2/src/App.vue
<template>
    <div>
        <h1>Pintura Image Editor</h1>

        <h2>Inline</h2>

        <div style="height: 70vh">
            <PinturaEditor
                v-bind="editorProps"
                :src="inlineSrc"
                @pintura:load="handleInlineLoad($event)"
                @pintura:process="handleInlineProcess($event)"
            />
        </div>

        <p v-if="inlineResult">
            <img :src="inlineResult" alt="" />
        </p>

        <h2>Modal</h2>

        <p>
            <button @click="modalVisible = true">Open editor</button>
        </p>

        <PinturaEditorModal
            v-bind="editorProps"
            v-if="modalVisible"
            :src="modalSrc"
            @pintura:hide="modalVisible = false"
            @pintura:show="handleModalShow()"
            @pintura:close="handleModalClose()"
            @pintura:load="handleModalLoad($event)"
            @pintura:process="handleModalProcess($event)"
        />

        <p v-if="modalResult">
            <img :src="modalResult" alt="" />
        </p>

        <h2>Overlay</h2>

        <p>
            <button v-if="!overlayVisible" @click="overlayVisible = true">Edit image</button>
            <button v-if="overlayVisible" @click="overlayVisible = false">Close editor</button>
        </p>

        <p v-if="!overlayVisible">
            <img :src="overlayResult.imagePreview || overlaySrc" width="512" height="256" alt="" />
        </p>

        <div v-if="overlayVisible" style="width: 512px; height: 256px">
            <PinturaEditorOverlay
                v-bind="editorProps"
                :src="overlaySrc"
                :imageState="overlayResult.imageState"
                @pintura:load="handleOverlayLoad($event)"
                @pintura:process="handleOverlayProcess($event)"
            />
        </div>

        <h2>FilePond</h2>

        <file-pond
            ref="pond"
            server="/api"
            accepted-file-types="image/jpeg, image/png"
            allow-multiple="true"
            :imageEditor="myEditor"
            :files="myFiles"
            @:init="handleFilePondInit"
        />
    </div>
</template>

<script>
// Import Vue FilePond
import vueFilePond from 'vue-filepond';
import FilePondPluginFilePoster from 'filepond-plugin-file-poster';
import FilePondPluginFileValidateType from 'filepond-plugin-file-validate-type';
import FilePondPluginImageEditor from 'filepond-plugin-image-editor';

// Import FilePond styles
import 'filepond/dist/filepond.min.css';
import 'filepond-plugin-file-poster/dist/filepond-plugin-file-poster.min.css';

// Import vue-pintura
import { PinturaEditor, PinturaEditorModal, PinturaEditorOverlay } from 'vue-pintura';

// Import pintura
import {
    // editor
    createDefaultImageReader,
    createDefaultImageWriter,
    createDefaultShapePreprocessor,
    locale_en_gb,

    // plugins
    setPlugins,
    plugin_crop,
    plugin_crop_locale_en_gb,
    plugin_filter,
    plugin_filter_defaults,
    plugin_filter_locale_en_gb,
    plugin_finetune,
    plugin_finetune_defaults,
    plugin_finetune_locale_en_gb,
    plugin_annotate,
    plugin_annotate_locale_en_gb,
    markup_editor_defaults,
    markup_editor_locale_en_gb,

    // filepond
    openEditor,
    processImage,
    createDefaultImageOrienter,
    legacyDataToImageState,
} from 'pintura';

setPlugins(plugin_crop, plugin_finetune, plugin_filter, plugin_annotate);

// Create FilePond component
const FilePond = vueFilePond(
    FilePondPluginFileValidateType,
    FilePondPluginImageEditor,
    FilePondPluginFilePoster
);

export default {
    name: 'App',
    components: {
        PinturaEditor,
        PinturaEditorModal,
        PinturaEditorOverlay,
        FilePond,
    },
    methods: {
        // inline
        handleInlineLoad: function (res) {
            console.log('inline load', res);
        },
        handleInlineProcess: function (res) {
            console.log('inline process', res);
            this.inlineResult = URL.createObjectURL(res.dest);
        },

        // modal
        handleModalLoad: function (res) {
            console.log('modal load', res);
        },
        handleModalShow: function () {
            console.log('modal show');
        },
        handleModalClose: function () {
            console.log('modal close');
        },
        handleModalProcess: function (res) {
            console.log('modal process', res);
            this.modalResult = URL.createObjectURL(res.dest);
        },

        // overlay
        handleOverlayLoad: function (res) {
            console.log('overlay load', res);
        },
        handleOverlayProcess: function (res) {
            console.log('overlay process', res);
            const { imageState, dest } = res;
            this.overlayResult = {
                imagePreview: URL.createObjectURL(dest),
                imageState: imageState,
            };
            this.overlayVisible = false;
        },

        // filepond
        handleFilePondInit: function () {
            console.log('FilePond has initialized');
            // FilePond instance methods are available on `this.$refs.pond`
        },
    },
    data() {
        return {
            // defaults
            editorProps: {
                imageReader: createDefaultImageReader(),
                imageWriter: createDefaultImageWriter(),
                shapePreprocessor: createDefaultShapePreprocessor(),
                ...plugin_finetune_defaults,
                ...plugin_filter_defaults,
                ...markup_editor_defaults,
                locale: {
                    ...locale_en_gb,
                    ...plugin_crop_locale_en_gb,
                    ...plugin_finetune_locale_en_gb,
                    ...plugin_filter_locale_en_gb,
                    ...plugin_annotate_locale_en_gb,
                    ...markup_editor_locale_en_gb,
                },
            },

            // inline state
            inlineSrc: 'image.jpeg',
            inlineResult: undefined,

            // modal state
            modalSrc: 'image.jpeg',
            modalVisible: false,
            modalResult: undefined,

            // overlay state
            overlaySrc: 'image.jpeg',
            overlayVisible: false,
            overlayResult: {
                imageState: undefined,
                imagePreview: undefined,
            },

            // filepond
            myEditor: {
                // map legacy data objects to new imageState objects
                legacyDataToImageState: legacyDataToImageState,

                // used to create the editor, receives editor configuration, should return an editor instance
                createEditor: openEditor,

                // Required, used for reading the image data
                imageReader: [createDefaultImageReader],

                // optionally. can leave out when not generating a preview thumbnail and/or output image
                imageWriter: [createDefaultImageWriter],

                // used to generate poster images, runs an editor in the background
                imageProcessor: processImage,

                // editor options
                editorOptions: {
                    imageOrienter: createDefaultImageOrienter(),
                    ...plugin_finetune_defaults,
                    ...plugin_filter_defaults,
                    ...markup_editor_defaults,
                    locale: {
                        ...locale_en_gb,
                        ...plugin_crop_locale_en_gb,
                        ...plugin_finetune_locale_en_gb,
                        ...plugin_filter_locale_en_gb,
                        ...plugin_annotate_locale_en_gb,
                        ...markup_editor_locale_en_gb,
                    },
                },
            },
            myFiles: [],
        };
    },
};
</script>

<style>
@import '../node_modules/pintura/pintura.css';

html {
    font-family: Avenir, Helvetica, Arial, sans-serif;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    color: #2c3e50;
}

h1 {
    margin-top: 0;
}

body {
    padding: 2em;
}

img {
    max-width: 100%;
}

.pintura-editor {
    box-shadow: 0 0 0 1px #eee;
}
</style>

// app/components/pintura/presets/angular/v9/src/app/app.component.ts
import { Component } from '@angular/core';
import { DomSanitizer } from '@angular/platform-browser';
import { FilePondOptions } from 'filepond';

// pintura
import {
    // editor
    locale_en_gb,
    createDefaultImageReader,
    createDefaultImageWriter,
    createDefaultShapePreprocessor,

    // plugins
    setPlugins,
    plugin_crop,
    plugin_crop_locale_en_gb,
    plugin_finetune,
    plugin_finetune_locale_en_gb,
    plugin_finetune_defaults,
    plugin_filter,
    plugin_filter_locale_en_gb,
    plugin_filter_defaults,
    plugin_annotate,
    plugin_annotate_locale_en_gb,
    markup_editor_defaults,
    markup_editor_locale_en_gb,

    // filepond
    legacyDataToImageState,
    openEditor,
    processImage,
} from 'pintura';

setPlugins(plugin_crop, plugin_finetune, plugin_filter, plugin_annotate);

@Component({
    selector: 'app-root',
    templateUrl: './app.component.html',
    styleUrls: [],
})
export class AppComponent {
    constructor(private sanitizer: DomSanitizer) {}

    // editor generic state
    editorOptions: any = {
        imageReader: createDefaultImageReader(),
        imageWriter: createDefaultImageWriter(),
        shapePreprocessor: createDefaultShapePreprocessor(),
        ...plugin_finetune_defaults,
        ...plugin_filter_defaults,
        ...markup_editor_defaults,
        locale: {
            ...locale_en_gb,
            ...plugin_crop_locale_en_gb,
            ...plugin_finetune_locale_en_gb,
            ...plugin_filter_locale_en_gb,
            ...plugin_annotate_locale_en_gb,
            ...markup_editor_locale_en_gb,
        },
    };

    // inline
    inlineSrc: string = 'assets/image.jpeg';
    inlineResult: string = undefined;

    handleInlineLoad($event) {
        console.log('inline load', $event);
    }

    handleInlineProcess($event) {
        console.log('inline process', $event);
        const objectURL = URL.createObjectURL($event.dest);
        this.inlineResult = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL) as string;
    }

    // modal
    modalSrc: string = 'assets/image.jpeg';
    modalResult: string = undefined;
    modalVisible: boolean = false;

    handleModalLoad($event) {
        console.log('modal load', $event);
    }

    handleModalProcess($event) {
        console.log('modal process', $event);
        const objectURL = URL.createObjectURL($event.dest);
        this.modalResult = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL) as string;
    }

    // overlay
    overlaySrc: string = 'assets/image.jpeg';
    overlayVisible: boolean = false;
    overlayResult: string = undefined;
    overlayOptions: any = {
        imageReader: createDefaultImageReader(),
        imageWriter: createDefaultImageWriter(),
        locale: {
            ...locale_en_gb,
            ...plugin_crop_locale_en_gb,
        },
    };

    handleOverlayLoad($event) {
        console.log('overlay load', $event);
    }

    handleOverlayProcess($event) {
        const objectURL = URL.createObjectURL($event.dest);
        this.overlayResult = this.sanitizer.bypassSecurityTrustResourceUrl(objectURL) as string;
        this.overlayOptions = {
            ...this.overlayOptions,
            imageState: $event.imageState,
        };

        this.overlayVisible = false;
    }

    // filepond
    pondOptions: FilePondOptions = {
        allowMultiple: true,
        labelIdle: 'Drop files here...',
        // FilePond Image Editor plugin properties
        imageEditor: {
            // Maps legacy data objects to new imageState objects (optional)
            legacyDataToImageState: legacyDataToImageState,

            // Used to create the editor (required)
            createEditor: openEditor,

            // Used for reading the image data. See JavaScript installation for details on the `imageReader` property (required)
            imageReader: [
                createDefaultImageReader,
                {
                    // createDefaultImageReader options here
                },
            ],

            // Can leave out when not generating a preview thumbnail and/or output image (required)
            imageWriter: [
                createDefaultImageWriter,
                {
                    // We'll resize images to fit a 512 × 512 square
                    targetSize: {
                        width: 512,
                        height: 512,
                    },
                },
            ],

            // Used to generate poster images, runs an invisible "headless" editor instance. (optional)
            imageProcessor: processImage,

            // Pintura Image Editor options
            editorOptions: {
                // The markup editor default options, tools, shape style controls
                ...markup_editor_defaults,

                // The finetune util controls
                ...plugin_finetune_defaults,

                // This handles complex shapes like arrows / frames
                shapePreprocessor: createDefaultShapePreprocessor(),

                // This will set a square crop aspect ratio
                imageCropAspectRatio: 1,

                // The icons and labels to use in the user interface (required)
                locale: {
                    ...locale_en_gb,
                    ...plugin_crop_locale_en_gb,
                    ...plugin_finetune_locale_en_gb,
                    ...plugin_annotate_locale_en_gb,
                    ...markup_editor_locale_en_gb,
                },
            },
        },
    };

    pondFiles: FilePondOptions['files'] = ['assets/image.jpeg'];

    pondHandleInit() {
        console.log('FilePond has initialised');
    }

    pondHandleAddFile(event: any) {
        console.log('A file was added', event);
    }

    pondHandlePrepareFile(event: any) {
        console.log('A file was prepared', event);
        // Append output image to page for testing
        // const url = URL.createObjectURL(event.output);
        // const img = new Image();
        // img.src = url;
        // document.body.append(img);
    }

    pondHandleActivateFile(event: any) {
        console.log('A file was activated', event);
    }
}

<style>
    :host {
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial,
            sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol';
        font-size: 14px;
        color: #333;
        box-sizing: border-box;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        padding: 2em;
    }

    img {
        max-width: 100%;
    }

    pintura-editor {
        box-shadow: 0 0 0 1px #eee;
    }
</style>

<div>
    <h1>Pintura Image Editor</h1>

    <h2>Inline</h2>

    <div style="height: 70vh">
        <pintura-editor
            [src]="inlineSrc"
            [options]="editorOptions"
            (load)="handleInlineLoad($event)"
            (process)="handleInlineProcess($event)"
        ></pintura-editor>
    </div>

    <p><img *ngIf="inlineResult" [src]="inlineResult" alt="" /></p>

    <h2>Modal</h2>

    <button (click)="modalVisible = true">Show Modal</button>

    <pintura-editor-modal
        *ngIf="modalVisible"
        [src]="modalSrc"
        [options]="editorOptions"
        (hide)="modalVisible = false"
        (load)="handleModalLoad($event)"
        (process)="handleModalProcess($event)"
    ></pintura-editor-modal>

    <p><img *ngIf="modalResult" [src]="modalResult" alt="" /></p>

    <h2>Overlay</h2>

    <p>
        <button *ngIf="!overlayVisible" (click)="overlayVisible = true">Edit image</button>
        <button *ngIf="overlayVisible" (click)="overlayVisible = false">Close editor</button>
    </p>

    <p *ngIf="!overlayVisible">
        <img [src]="overlayResult || overlaySrc" width="512" height="256" alt="" />
    </p>

    <div *ngIf="overlayVisible" style="width: 512px; height: 256px">
        <pintura-editor-overlay
            [src]="overlaySrc"
            [options]="overlayOptions"
            (load)="handleOverlayLoad($event)"
            (process)="handleOverlayProcess($event)"
        ></pintura-editor-overlay>
    </div>

    <h2>FilePond</h2>

    <file-pond
        #myPond
        [options]="pondOptions"
        [files]="pondFiles"
        (oninit)="pondHandleInit()"
        (onaddfile)="pondHandleAddFile($event)"
        (onactivatefile)="pondHandleActivateFile($event)"
        (onpreparefile)="pondHandlePrepareFile($event)"
    >
    </file-pond>
</div>
